# @package experiment.config

do_train: true
train_env_interface_args:
  parent_to_child_mapping: null
  object_names:
    - 021_logo_tbp
    - 022_logo_numenta
train_env_interface_class: ${monty.class:tbp.monty.experiment.environment.OneObjectPerEpisodeInterface}
